import '../../complete_text/response/usage.dart';

class OpenAiResponseData {
  /// The unique ID of the Response.
  final String? id;

  /// The object type, always set to "response".
  final String? object;

  /// The status of the Response (e.g. "in_progress", "completed", "incomplete", "failed").
  final String? status;

  /// The model used to generate this Response.
  final String? model;

  /// The list of generated output items (messages, tool calls, search results, etc.).
  final List<ResponseOutputItem>? output;

  /// Usage statistics for the request.
  final Usage? usage;

  OpenAiResponseData({
    this.id,
    this.object,
    this.status,
    this.model,
    this.output,
    this.usage,
  });

  /// Convenience getter to easily fetch the first generated output text content.
  /// This iterates over all output items, inspects their content parts,
  /// and returns the first part with type 'output_text'.
  String get outputText {
    if (output == null) return '';
    for (var item in output!) {
      if (item.content != null) {
        for (var part in item.content!) {
          if (part.type == 'output_text' && part.text != null) {
            return part.text!;
          }
        }
      }
    }
    return '';
  }

  factory OpenAiResponseData.fromJson(Map<String, dynamic> json) {
    return OpenAiResponseData(
      id: json['id'] as String?,
      object: json['object'] as String?,
      status: json['status'] as String?,
      model: json['model'] as String?,
      output: json['output'] != null
          ? (json['output'] as List)
              .map((e) => ResponseOutputItem.fromJson(e as Map<String, dynamic>))
              .toList()
          : null,
      usage: json['usage'] != null
          ? Usage.fromJson(json['usage'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'object': object,
        'status': status,
        'model': model,
        if (output != null) 'output': output?.map((e) => e.toJson()).toList(),
        if (usage != null) 'usage': usage?.toJson(),
      }..removeWhere((key, value) => value == null);
}

class ResponseOutputItem {
  /// The unique ID of the output item.
  final String? id;

  /// The type of the output item (e.g. "message", "file_search_call", etc.).
  final String? type;

  /// The status of the output item.
  final String? status;

  /// The role of the output message, if the item is a message (typically "assistant").
  final String? role;

  /// The list of content parts for this output item.
  final List<ResponseContentPart>? content;

  ResponseOutputItem({
    this.id,
    this.type,
    this.status,
    this.role,
    this.content,
  });

  factory ResponseOutputItem.fromJson(Map<String, dynamic> json) {
    return ResponseOutputItem(
      id: json['id'] as String?,
      type: json['type'] as String?,
      status: json['status'] as String?,
      role: json['role'] as String?,
      content: json['content'] != null
          ? (json['content'] as List)
              .map((e) => ResponseContentPart.fromJson(e as Map<String, dynamic>))
              .toList()
          : null,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'type': type,
        'status': status,
        'role': role,
        if (content != null) 'content': content?.map((e) => e.toJson()).toList(),
      }..removeWhere((key, value) => value == null);
}

class ResponseContentPart {
  /// The type of the content part (e.g. "output_text", "refusal", etc.).
  final String? type;

  /// The actual text generated by the model.
  final String? text;

  ResponseContentPart({this.type, this.text});

  factory ResponseContentPart.fromJson(Map<String, dynamic> json) {
    return ResponseContentPart(
      type: json['type'] as String?,
      text: json['text'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'type': type,
        'text': text,
      }..removeWhere((key, value) => value == null);
}
